name: BuildTest

# Every push, we do build and testing process.
on: push

jobs:
  BuildLinux:
    # Name the Job
    name: Build on Linux

    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Build operation
      - name: Compiling Code
        run: |
          ./gradlew clean build --info --stacktrace

      # Run Test operation
      - name: Testing Code
        run: |
          ./gradlew clean test --info --stacktrace

  BuildWindows:
      # Name the Job
      name: Build on Windows

      # Set the type of machine to run on
      runs-on: windows-latest

      steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
        - name: Checkout code
          uses: actions/checkout@v2

        # Run Build operation
        - name: Compiling Code
          run: |
             ./gradlew.bat clean build --info --stacktrace

        # Run Test operation
        - name: Testing Code
          run: |
            ./gradlew.bat clean test --info --stacktrace

  BuildmacOS:
    # Name the Job
    name: Build on macOS

    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Build operation
      - name: Compiling Code
        run: |
          ./gradlew clean build --info --stacktrace

      # Run Test operation
      - name: Testing Code
        run: |
          ./gradlew clean test --info --stacktrace